build:
	npx @marp-team/marp-cli@latest hop3-presentation.md \
		-o hop3.html --allow-local-files
	npx @marp-team/marp-cli@latest hop3-presentation.md \
		-o hop3.pdf --allow-local-files

dev:
#	npx @marp-team/marp-cli@latest -s -w hop3-presentation.md \
#		--allow-local-files
	npx @marp-team/marp-cli@latest -s -w \
		--allow-local-files .
